languageCode = "en-us"
title = "Secure Foundation"
baseURL = "https://jacksingleton.github.io/securefoundation/"
theme = "hugo-theme-minos"
MetaDataFormat = "yaml"

[taxonomies]
context = "contexts"
type = "types"
threat = "threats"
